"""PDF report builder using ReportLab Platypus."""

from __future__ import annotations

import io
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib.colors import white, black
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
    HRFlowable,
    Image,
)

from .models import NucleiFinding, ScanReport, Severity
from .charts import severity_bar_chart, severity_donut_chart
from .styles import (
    PAGE_SIZE,
    PAGE_WIDTH,
    PAGE_HEIGHT,
    MARGIN,
    CONTENT_WIDTH,
    SEVERITY_COLORS,
    SEVERITY_BG_COLORS,
    DARK_BG,
    ACCENT,
    LIGHT_GREY,
    BORDER_GREY,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    get_styles,
)


def _esc(text: str | None) -> str:
    """Escape text for safe use in ReportLab XML paragraphs."""
    if not text:
        return ""
    return escape(str(text))


class ReportBuilder:
    """Builds a multi-page PDF vulnerability assessment report."""

    def __init__(self, report: ScanReport, output_path: str | Path) -> None:
        self.report = report
        self.output_path = Path(output_path)
        self.styles = get_styles()
        self.story: list = []

    def build(self) -> Path:
        """Generate the PDF and return the output path."""
        doc = SimpleDocTemplate(
            str(self.output_path),
            pagesize=PAGE_SIZE,
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            topMargin=MARGIN,
            bottomMargin=MARGIN,
        )

        self._add_cover_page()
        self._add_executive_summary()
        self._add_findings_sections()
        self._add_appendices()

        doc.build(self.story, onFirstPage=self._header_footer, onLaterPages=self._header_footer)
        return self.output_path

    # ------------------------------------------------------------------
    # Header / Footer
    # ------------------------------------------------------------------

    def _header_footer(self, canvas, doc):
        """Draw header and footer on every page."""
        canvas.saveState()
        page_num = canvas.getPageNumber()

        # Skip header on page 1 (cover page)
        if page_num > 1:
            # Header bar
            canvas.setFillColor(LIGHT_GREY)
            canvas.rect(MARGIN, PAGE_HEIGHT - MARGIN + 8, CONTENT_WIDTH, 20, fill=1, stroke=0)
            canvas.setFillColor(TEXT_SECONDARY)
            canvas.setFont("Helvetica", 8)
            canvas.drawString(MARGIN + 6, PAGE_HEIGHT - MARGIN + 14, self.report.title)
            canvas.drawRightString(
                PAGE_WIDTH - MARGIN - 6,
                PAGE_HEIGHT - MARGIN + 14,
                f"Page {page_num}",
            )

        # Footer on every page
        canvas.setFillColor(TEXT_SECONDARY)
        canvas.setFont("Helvetica", 7)
        canvas.drawString(
            MARGIN,
            MARGIN - 20,
            f"Generated by NucleiReport | {self.report.generated_at:%Y-%m-%d %H:%M}",
        )
        canvas.drawRightString(
            PAGE_WIDTH - MARGIN,
            MARGIN - 20,
            "CONFIDENTIAL",
        )

        canvas.restoreState()

    # ------------------------------------------------------------------
    # Cover Page
    # ------------------------------------------------------------------

    def _add_cover_page(self):
        """Build the cover page with dark background effect."""
        s = self.styles

        self.story.append(Spacer(1, 1.5 * inch))

        cover_data = []

        # Title
        cover_data.append([Paragraph(
            _esc(self.report.title),
            s["cover_title"],
        )])

        cover_data.append([Spacer(1, 8)])

        # Scan metadata
        target_count = len(self.report.targets)
        finding_count = self.report.total_findings
        date_str = self.report.generated_at.strftime("%B %d, %Y")

        meta_lines = [
            f"{target_count} targets scanned  |  {finding_count} findings",
            f"Report generated: {date_str}",
        ]
        if self.report.scan_time_range[0]:
            scan_start = self.report.scan_time_range[0][:19]
            meta_lines.append(f"Scan period: {scan_start}")

        for line in meta_lines:
            cover_data.append([Paragraph(line, s["cover_subtitle"])])

        cover_data.append([Spacer(1, 16)])

        # Severity summary badges
        badge_parts = []
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = self.report.severity_counts.get(sev, 0)
            if count > 0:
                color = SEVERITY_COLORS[sev].hexval()
                badge_parts.append(
                    f'<font color="#{color}"><b>{count}</b> {sev.upper()}</font>'
                )
        if badge_parts:
            cover_data.append([Paragraph(
                " &nbsp;&nbsp; | &nbsp;&nbsp; ".join(badge_parts),
                s["cover_subtitle"],
            )])

        cover_table = Table(cover_data, colWidths=[CONTENT_WIDTH - 40])
        cover_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), DARK_BG),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 20),
            ("RIGHTPADDING", (0, 0), (-1, -1), 20),
            ("ROUNDEDCORNERS", [8, 8, 8, 8]),
        ]))
        self.story.append(cover_table)

        self.story.append(Spacer(1, 1 * inch))

        self.story.append(Paragraph(
            "Generated by <b>NucleiReport</b> | Nuclei Vulnerability Scanner",
            s["body_secondary"],
        ))

        self.story.append(PageBreak())

    # ------------------------------------------------------------------
    # Executive Summary
    # ------------------------------------------------------------------

    def _add_executive_summary(self):
        """Build the executive summary page with chart and stats."""
        s = self.styles

        self.story.append(Paragraph("Executive Summary", s["section_title"]))
        self.story.append(HRFlowable(
            width="100%", thickness=1, color=BORDER_GREY, spaceAfter=12,
        ))

        # Risk overview paragraph
        crit = self.report.severity_counts.get("critical", 0)
        high = self.report.severity_counts.get("high", 0)
        total = self.report.total_findings

        if crit > 0:
            risk_text = (
                f"This assessment identified <b>{total} findings</b> across "
                f"{len(self.report.targets)} targets. "
                f"<font color='#{SEVERITY_COLORS['critical'].hexval()}'>"
                f"<b>{crit} critical</b></font> and "
                f"<font color='#{SEVERITY_COLORS['high'].hexval()}'>"
                f"<b>{high} high</b></font> severity issues require immediate attention."
            )
        elif high > 0:
            risk_text = (
                f"This assessment identified <b>{total} findings</b> across "
                f"{len(self.report.targets)} targets. "
                f"<font color='#{SEVERITY_COLORS['high'].hexval()}'>"
                f"<b>{high} high</b></font> severity issues should be prioritized."
            )
        else:
            risk_text = (
                f"This assessment identified <b>{total} findings</b> across "
                f"{len(self.report.targets)} targets. "
                "No critical or high severity issues were found."
            )

        self.story.append(Paragraph(risk_text, s["body"]))
        self.story.append(Spacer(1, 16))

        # --- Charts side by side: bar chart + donut chart ---
        bar_png = severity_bar_chart(self.report.severity_counts)
        donut_png = severity_donut_chart(self.report.severity_counts)

        bar_img = Image(io.BytesIO(bar_png), width=3.6 * inch, height=1.7 * inch)
        donut_img = Image(io.BytesIO(donut_png), width=2.2 * inch, height=2.2 * inch)

        chart_table = Table(
            [[bar_img, donut_img]],
            colWidths=[3.8 * inch, 2.7 * inch],
        )
        chart_table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        self.story.append(chart_table)
        self.story.append(Spacer(1, 16))

        # --- Severity breakdown table ---
        self.story.append(Paragraph("Findings by Severity", s["heading"]))
        self.story.append(Spacer(1, 6))

        table_data = [["Severity", "Count", "Percentage"]]
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = self.report.severity_counts.get(sev, 0)
            pct = f"{(count / total * 100):.1f}%" if total > 0 else "0.0%"
            table_data.append([sev.upper(), str(count), pct])
        table_data.append(["TOTAL", str(total), "100.0%"])

        severity_table = Table(table_data, colWidths=[2.2 * inch, 1.5 * inch, 1.5 * inch])
        severity_table.setStyle(TableStyle([
            # Header row
            ("BACKGROUND", (0, 0), (-1, 0), DARK_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("TOPPADDING", (0, 0), (-1, 0), 8),
            # Severity color on first column
            ("TEXTCOLOR", (0, 1), (0, 1), SEVERITY_COLORS["critical"]),
            ("TEXTCOLOR", (0, 2), (0, 2), SEVERITY_COLORS["high"]),
            ("TEXTCOLOR", (0, 3), (0, 3), SEVERITY_COLORS["medium"]),
            ("TEXTCOLOR", (0, 4), (0, 4), SEVERITY_COLORS["low"]),
            ("TEXTCOLOR", (0, 5), (0, 5), SEVERITY_COLORS["info"]),
            # Total row
            ("BACKGROUND", (0, -1), (-1, -1), LIGHT_GREY),
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            # General
            ("FONTNAME", (0, 1), (0, -2), "Helvetica-Bold"),
            ("FONTSIZE", (0, 1), (-1, -1), 10),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 1), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("GRID", (0, 0), (-1, -1), 0.5, BORDER_GREY),
        ]))
        self.story.append(severity_table)
        self.story.append(Spacer(1, 20))

        # --- Top critical findings ---
        if self.report.top_critical:
            self.story.append(Paragraph("Top Critical Findings", s["heading"]))
            self.story.append(Spacer(1, 6))

            for i, finding in enumerate(self.report.top_critical, 1):
                sev = finding.info.severity.value
                color = SEVERITY_COLORS[sev].hexval()
                cvss_str = f" (CVSS {finding.cvss_score})" if finding.cvss_score else ""
                line = (
                    f'{i}. <font color="#{color}"><b>[{sev.upper()}]</b></font> '
                    f'{_esc(finding.info.name)}{cvss_str} - '
                    f'<font color="#{TEXT_SECONDARY.hexval()}">{_esc(finding.host)}</font>'
                )
                self.story.append(Paragraph(line, s["body"]))

        self.story.append(PageBreak())

    # ------------------------------------------------------------------
    # Findings Sections
    # ------------------------------------------------------------------

    def _add_findings_sections(self):
        """Build the detailed findings pages, grouped by severity."""
        s = self.styles
        severity_order = ["critical", "high", "medium", "low", "info"]

        self.story.append(Paragraph("Detailed Findings", s["section_title"]))
        self.story.append(HRFlowable(
            width="100%", thickness=1, color=BORDER_GREY, spaceAfter=12,
        ))

        first_section = True
        finding_num = 0

        for sev in severity_order:
            findings = self.report.findings_by_severity.get(sev, [])
            if not findings:
                continue

            # Page break between severity sections (except before the first)
            if not first_section:
                self.story.append(PageBreak())
                self.story.append(Paragraph("Detailed Findings (continued)", s["section_title"]))
                self.story.append(HRFlowable(
                    width="100%", thickness=1, color=BORDER_GREY, spaceAfter=12,
                ))
            first_section = False

            color = SEVERITY_COLORS[sev]

            # Severity section header banner
            header_data = [[Paragraph(
                f'<font color="#FFFFFF"><b>{sev.upper()} - {len(findings)} '
                f'finding{"s" if len(findings) != 1 else ""}</b></font>',
                s["body"],
            )]]
            header_table = Table(header_data, colWidths=[CONTENT_WIDTH])
            header_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), color),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("LEFTPADDING", (0, 0), (-1, -1), 14),
                ("ROUNDEDCORNERS", [4, 4, 4, 4]),
            ]))
            self.story.append(header_table)
            self.story.append(Spacer(1, 12))

            # Individual finding cards
            for finding in findings:
                finding_num += 1
                card = self._build_finding_card(finding, finding_num, sev)
                self.story.append(KeepTogether(card))
                self.story.append(Spacer(1, 12))

    def _build_finding_card(
        self,
        finding: NucleiFinding,
        number: int,
        sev: str,
    ) -> list:
        """Build a styled card for a single finding. Returns list of flowables."""
        s = self.styles
        color = SEVERITY_COLORS[sev]
        bg = SEVERITY_BG_COLORS[sev]

        # Card header: severity badge + name + CVSS
        cvss_str = ""
        if finding.cvss_score:
            cvss_str = f" | CVSS: {finding.cvss_score}"
        cve_str = ""
        if finding.info.classification and finding.info.classification.cve_id:
            cve_str = " | " + ", ".join(finding.info.classification.cve_id)

        header_text = (
            f'<font color="#{color.hexval()}"><b>[{sev.upper()}]</b></font> '
            f'<b>{_esc(finding.info.name)}</b>'
            f'<font color="#{TEXT_SECONDARY.hexval()}">{cve_str}{cvss_str}</font>'
        )

        card_rows = []

        # Header
        card_rows.append([Paragraph(header_text, s["finding_name"])])

        # Template ID
        card_rows.append([Paragraph(
            f'<font color="#{TEXT_SECONDARY.hexval()}">Template: {_esc(finding.template_id)}</font>',
            s["small"],
        )])

        # Description
        if finding.info.description:
            card_rows.append([Spacer(1, 4)])
            card_rows.append([Paragraph(_esc(finding.info.description), s["finding_body"])])

        # Target info
        card_rows.append([Spacer(1, 6)])
        target_text = f'<b>Target:</b> {_esc(finding.host)}'
        if finding.matched_at and finding.matched_at != finding.host:
            target_text += f'<br/><b>Matched At:</b> {_esc(finding.matched_at)}'
        if finding.ip:
            target_text += f'<br/><b>IP:</b> {_esc(finding.ip)}'
        card_rows.append([Paragraph(target_text, s["finding_body"])])

        # CVSS vector
        if finding.info.classification and finding.info.classification.cvss_metrics:
            card_rows.append([Spacer(1, 2)])
            card_rows.append([Paragraph(
                f'<b>CVSS Vector:</b> {_esc(finding.info.classification.cvss_metrics)}',
                s["small"],
            )])

        # Remediation
        if finding.info.remediation:
            card_rows.append([Spacer(1, 6)])
            # Remediation in a highlighted sub-block
            remed_data = [[Paragraph(
                f'<b>Remediation:</b> {_esc(finding.info.remediation)}',
                s["finding_body"],
            )]]
            remed_table = Table(remed_data, colWidths=[CONTENT_WIDTH - 50])
            remed_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GREY),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("ROUNDEDCORNERS", [3, 3, 3, 3]),
            ]))
            card_rows.append([remed_table])

        # References
        if finding.info.reference:
            card_rows.append([Spacer(1, 4)])
            ref_lines = "<b>References:</b><br/>"
            for ref in finding.info.reference:
                ref_lines += f'  - <link href="{_esc(ref)}">{_esc(ref)}</link><br/>'
            card_rows.append([Paragraph(ref_lines, s["reference_link"])])

        # Build the card as a bordered table with left accent
        card_table = Table(card_rows, colWidths=[CONTENT_WIDTH - 24])
        card_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), bg),
            ("TOPPADDING", (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            # Extra padding on first/last rows
            ("TOPPADDING", (0, 0), (-1, 0), 10),
            ("BOTTOMPADDING", (0, -1), (-1, -1), 10),
            # Left accent border
            ("LINEBEFORE", (0, 0), (0, -1), 3, color),
            # Outer border
            ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GREY),
        ]))

        return [card_table]

    # ------------------------------------------------------------------
    # Appendices
    # ------------------------------------------------------------------

    def _add_appendices(self):
        """Build appendix pages: targets, scan metadata, severity definitions."""
        s = self.styles

        self.story.append(PageBreak())
        self.story.append(Paragraph("Appendices", s["section_title"]))
        self.story.append(HRFlowable(
            width="100%", thickness=1, color=BORDER_GREY, spaceAfter=16,
        ))

        # --- A. Targets Scanned ---
        self.story.append(Paragraph("A. Targets Scanned", s["heading"]))
        self.story.append(Spacer(1, 6))

        target_data = [["#", "Host", "Findings"]]
        # Count findings per host
        host_counts: dict[str, int] = {}
        for findings_list in self.report.findings_by_severity.values():
            for f in findings_list:
                host_counts[f.host] = host_counts.get(f.host, 0) + 1

        for i, target in enumerate(self.report.targets, 1):
            count = host_counts.get(target, 0)
            target_data.append([str(i), target, str(count)])

        target_table = Table(target_data, colWidths=[0.5 * inch, 4.0 * inch, 1.0 * inch])
        target_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), DARK_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
            ("ALIGN", (2, 0), (2, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, BORDER_GREY),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, LIGHT_GREY]),
        ]))
        self.story.append(target_table)
        self.story.append(Spacer(1, 24))

        # --- B. Scan Metadata ---
        self.story.append(Paragraph("B. Scan Metadata", s["heading"]))
        self.story.append(Spacer(1, 6))

        meta_items = [
            ["Total Findings", str(self.report.total_findings)],
            ["Unique Targets", str(len(self.report.targets))],
            ["Report Generated", self.report.generated_at.strftime("%Y-%m-%d %H:%M:%S")],
        ]
        if self.report.scan_time_range[0]:
            meta_items.append(["Scan Start", self.report.scan_time_range[0][:19]])
        if self.report.scan_time_range[1]:
            meta_items.append(["Scan End", self.report.scan_time_range[1][:19]])

        # Severity breakdown rows
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = self.report.severity_counts.get(sev, 0)
            meta_items.append([f"{sev.capitalize()} Findings", str(count)])

        meta_table = Table(meta_items, colWidths=[2.0 * inch, 3.5 * inch])
        meta_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1), TEXT_SECONDARY),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, BORDER_GREY),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [white, LIGHT_GREY]),
        ]))
        self.story.append(meta_table)
        self.story.append(Spacer(1, 24))

        # --- C. Severity Definitions ---
        self.story.append(Paragraph("C. Severity Definitions", s["heading"]))
        self.story.append(Spacer(1, 6))

        desc_style = s["finding_body"]
        definitions = [
            ["Severity", "CVSS Range", "Description"],
            ["CRITICAL", "9.0 - 10.0",
             Paragraph("Exploitation is straightforward and usually results in system-level compromise. Immediate remediation is required.", desc_style)],
            ["HIGH", "7.0 - 8.9",
             Paragraph("Exploitation is possible with moderate complexity. Could result in significant data loss or system impact.", desc_style)],
            ["MEDIUM", "4.0 - 6.9",
             Paragraph("Exploitation requires specific conditions. Impact is limited but could escalate if combined with other vulnerabilities.", desc_style)],
            ["LOW", "0.1 - 3.9",
             Paragraph("Exploitation is difficult or impact is minimal. Should be addressed as part of regular maintenance.", desc_style)],
            ["INFO", "0.0",
             Paragraph("Informational finding with no direct security impact. Useful for understanding the target's configuration.", desc_style)],
        ]

        def_table = Table(definitions, colWidths=[1.2 * inch, 1.0 * inch, 4.3 * inch])
        def_table.setStyle(TableStyle([
            # Header
            ("BACKGROUND", (0, 0), (-1, 0), DARK_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            # Severity colors
            ("TEXTCOLOR", (0, 1), (0, 1), SEVERITY_COLORS["critical"]),
            ("TEXTCOLOR", (0, 2), (0, 2), SEVERITY_COLORS["high"]),
            ("TEXTCOLOR", (0, 3), (0, 3), SEVERITY_COLORS["medium"]),
            ("TEXTCOLOR", (0, 4), (0, 4), SEVERITY_COLORS["low"]),
            ("TEXTCOLOR", (0, 5), (0, 5), SEVERITY_COLORS["info"]),
            ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
            # General
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.5, BORDER_GREY),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, LIGHT_GREY]),
        ]))
        self.story.append(def_table)

        # --- D. Compact Findings Reference ---
        self.story.append(Spacer(1, 24))
        self.story.append(Paragraph("D. Findings Quick Reference", s["heading"]))
        self.story.append(Spacer(1, 6))

        ref_data = [["#", "Severity", "Name", "Target", "CVSS"]]
        finding_num = 0
        for sev in ["critical", "high", "medium", "low", "info"]:
            for f in self.report.findings_by_severity.get(sev, []):
                finding_num += 1
                cvss = str(f.cvss_score) if f.cvss_score else "-"
                # Truncate long names
                name = f.info.name
                if len(name) > 35:
                    name = name[:32] + "..."
                host = f.host
                if len(host) > 30:
                    host = host[:27] + "..."
                ref_data.append([
                    str(finding_num),
                    sev.upper()[:4],
                    name,
                    host,
                    cvss,
                ])

        ref_table = Table(
            ref_data,
            colWidths=[0.4 * inch, 0.6 * inch, 2.4 * inch, 2.1 * inch, 0.6 * inch],
            repeatRows=1,
        )
        ref_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), DARK_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
            ("ALIGN", (4, 0), (4, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, BORDER_GREY),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, LIGHT_GREY]),
        ]))
        self.story.append(ref_table)


def generate_report(report: ScanReport, output_path: str | Path) -> Path:
    """Convenience function to generate a PDF report.

    Args:
        report: Processed ScanReport from the processor.
        output_path: Where to write the PDF file.

    Returns:
        Path to the generated PDF.
    """
    builder = ReportBuilder(report, output_path)
    return builder.build()
